name: MP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'mp/src/**'
  pull_request:
   paths:
      - 'mp/src/**'

jobs:
  build:
    runs-on:
      windows-2019
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        

      - name: Configure registry
        shell: powershell
        run: |
          REG ADD "HKLM\Software\Microsoft\VisualStudio\12.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v "DefaultProjectExtension" /t REG_SZ  /d "vcxproj" /f /reg:32
          REG ADD "HKLM\Software\Microsoft\VisualStudio\12.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v "PossibleProjectExtensions" /t REG_SZ /d "vcxproj;vcxitems;vcproj;mak" /f /reg:32

      - name: Create project
        run: cd mp/src;devtools/bin/vpc.exe /sdk2013ce /2013 +game /mksln sdk2013ce.sln

      - name: Build project
        run: cd mp/src;devenv sdk2013ce.sln /Build Release

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz mp/game/mod_sdk2013ce/bin

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: mp_sdk2013ce
          path: Windows.tar.xz
